# Generated by Django 5.0.7 on 2024-10-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0002_rename_estado_de_la_propiedad_alquiler_condiciones_de_la_propiedad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='estado',
        ),
    ]
