# Generated by Django 5.0.7 on 2024-10-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0003_remove_alquiler_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terreno',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='terreno',
            name='tipo_de_terreno',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='cuarto_de_servicio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='imagen10',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='imagen11',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='imagen12',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='imagen13',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='imagen14',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='imagen15',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='imagen16',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='imagen9',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp'),
        ),
        migrations.AddField(
            model_name='preconstruccion',
            name='cuarto_de_servicio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preconstruccion',
            name='imagen10',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp'),
        ),
        migrations.AddField(
            model_name='preconstruccion',
            name='imagen11',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp'),
        ),
        migrations.AddField(
            model_name='preconstruccion',
            name='imagen12',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp'),
        ),
        migrations.AddField(
            model_name='preconstruccion',
            name='imagen13',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp'),
        ),
        migrations.AddField(
            model_name='preconstruccion',
            name='imagen14',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp'),
        ),
        migrations.AddField(
            model_name='preconstruccion',
            name='imagen15',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp'),
        ),
        migrations.AddField(
            model_name='preconstruccion',
            name='imagen16',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp'),
        ),
        migrations.AddField(
            model_name='preconstruccion',
            name='imagen9',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp'),
        ),
    ]
