# Generated by Django 5.0.7 on 2024-10-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0005_venta_imagen10_venta_imagen11_venta_imagen12_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alquiler',
            options={'verbose_name': 'Renta', 'verbose_name_plural': 'Rentas'},
        ),
        migrations.AlterModelOptions(
            name='preconstruccion',
            options={'verbose_name': 'Pre-Venta', 'verbose_name_plural': 'Pre-ventas'},
        ),
        migrations.AddField(
            model_name='venta',
            name='cuarto_de_servicio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
