# Generated by Django 5.0.7 on 2024-10-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0006_alter_alquiler_options_alter_preconstruccion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preconstruccion',
            name='alcantarillado',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='alcantarillado',
        ),
    ]
