# Generated by Django 5.0.7 on 2024-10-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0007_remove_preconstruccion_alcantarillado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='vista_primaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='vista_secundaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
