# Generated by Django 5.0.7 on 2024-10-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0008_alquiler_vista_primaria_alquiler_vista_secundaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='aire_acondicionado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='calentador_de_agua',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='tipo_tipo_de_estufa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
