# Generated by Django 5.0.7 on 2024-11-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0009_alquiler_aire_acondicionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
