# Generated by Django 5.0.7 on 2024-11-01 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0010_venta_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='likes',
        ),
    ]
