# Generated by Django 5.0.7 on 2024-11-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0011_remove_venta_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preconstruccion',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='preconstruccion',
            name='habitaciones',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='preconstruccion',
            name='informacion_extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
