# Generated by Django 5.0.7 on 2024-11-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0012_remove_preconstruccion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preconstruccion',
            name='cocina',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='preconstruccion',
            name='fecha_entrega',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
