# Generated by Django 5.0.7 on 2024-11-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0013_preconstruccion_cocina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preconstruccion',
            name='numero_de_departamento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
