# Generated by Django 5.0.7 on 2024-11-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0014_preconstruccion_numero_de_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfilamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.CharField(max_length=10)),
                ('estado_civil', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=255)),
                ('colonia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('rfc', models.CharField(max_length=20)),
                ('curp', models.CharField(max_length=20)),
                ('numero_identificacion_oficial', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=100)),
                ('numero_exterior', models.CharField(max_length=10)),
                ('tipo_inmueble', models.CharField(max_length=50)),
                ('num_plantas', models.CharField(max_length=10)),
                ('cocina', models.CharField(max_length=50)),
                ('num_recamaras', models.CharField(max_length=10)),
                ('sala_estar', models.CharField(max_length=50)),
                ('num_banos', models.CharField(max_length=10)),
                ('comedor', models.CharField(max_length=50)),
                ('estacionamiento', models.CharField(max_length=10)),
                ('estudio', models.CharField(max_length=50)),
                ('superficie_terreno', models.CharField(max_length=10)),
                ('superficie_construccion', models.CharField(max_length=10)),
                ('uso_suelo', models.CharField(max_length=50)),
                ('antiguedad', models.CharField(max_length=10)),
                ('forma_adquisicion', models.CharField(max_length=50)),
                ('grabamenes_propiedad', models.CharField(max_length=255)),
                ('jardin', models.CharField(max_length=50)),
                ('paneles_solares', models.CharField(max_length=50)),
                ('aire_acondicionado', models.CharField(max_length=50)),
                ('alberca', models.CharField(max_length=50)),
            ],
        ),
    ]
