# Generated by Django 5.0.7 on 2024-11-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0015_perfilamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_conservacion', models.CharField(max_length=255)),
                ('superficie_terreno', models.FloatField(help_text='Superficie en metros cuadrados')),
                ('superficie_construccion', models.FloatField(help_text='Superficie en metros cuadrados')),
                ('instalaciones_especiales', models.TextField(blank=True, help_text='Descripción de instalaciones especiales')),
                ('distribucion_materiales', models.TextField(blank=True, help_text='Distribución y materiales de construcción en general')),
                ('infraestructura_zona', models.TextField(blank=True, help_text='Infraestructura de la zona y urbanización')),
                ('antiguedad', models.IntegerField(help_text='Antigüedad en años')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('situacion_legal', models.TextField(blank=True, help_text='Descripción de la situación legal')),
                ('foto_1', models.ImageField(blank=True, null=True, upload_to='inmuebles/fotos/')),
                ('foto_2', models.ImageField(blank=True, null=True, upload_to='inmuebles/fotos/')),
                ('foto_3', models.ImageField(blank=True, null=True, upload_to='inmuebles/fotos/')),
                ('foto_4', models.ImageField(blank=True, null=True, upload_to='inmuebles/fotos/')),
            ],
        ),
    ]
