# Generated by Django 5.0.7 on 2024-11-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0017_fichatecnica_urbanizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_propietario', models.CharField(max_length=255)),
                ('direccion_del_inmueble', models.CharField(max_length=255)),
                ('estado_de_conservacion', models.CharField(max_length=255)),
                ('superficie_de_terreno', models.CharField(max_length=255)),
                ('superficie_de_construccion', models.CharField(max_length=255)),
                ('instalaciones_especiales', models.CharField(max_length=255)),
                ('distribucion', models.CharField(max_length=255)),
                ('materiales_de_construccion', models.CharField(max_length=255)),
                ('acabados', models.CharField(max_length=255)),
                ('equipamiento_general', models.CharField(max_length=255)),
                ('infraestructura_y_urbanizacion', models.CharField(max_length=255)),
                ('antiguedad_de_la_construccion', models.CharField(max_length=255)),
            ],
        ),
    ]
