# Generated by Django 5.0.7 on 2024-11-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0019_infoextra_calle_infoextra_ciudad_infoextra_colonia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoextra',
            name='direccion_del_inmueble',
        ),
    ]
