# Generated by Django 5.0.7 on 2024-11-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0022_alquiler_balcon_alquiler_cocina_alquiler_comedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preconstruccion',
            name='escrituras',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
