# Generated by Django 5.0.7 on 2024-11-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0023_preconstruccion_escrituras'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='sala',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='antiguedad',
            field=models.CharField(help_text='Antigüedad en años', max_length=250),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='distribucion_materiales',
            field=models.CharField(blank=True, help_text='Distribución y materiales de construcción en general', max_length=250),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='estado_conservacion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='infraestructura_zona',
            field=models.CharField(blank=True, help_text='Infraestructura de la zona y urbanización', max_length=250),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='instalaciones_especiales',
            field=models.CharField(blank=True, help_text='Descripción de instalaciones especiales', max_length=250),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='precio_venta',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='situacion_legal',
            field=models.CharField(blank=True, help_text='Descripción de la situación legal', max_length=250),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='superficie_construccion',
            field=models.CharField(help_text='Superficie en metros cuadrados', max_length=250),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='superficie_terreno',
            field=models.CharField(help_text='Superficie en metros cuadrados', max_length=250),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='urbanizacion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
