# Generated by Django 5.0.7 on 2024-11-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0024_venta_sala_alter_fichatecnica_antiguedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preconstruccion',
            name='medidas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preconstruccion',
            name='metros_cuadrados',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
