# Generated by Django 5.0.7 on 2024-11-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0025_preconstruccion_medidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilamiento',
            name='cargo_en_la_agencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfilamiento',
            name='ciudad_y_estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfilamiento',
            name='email_agente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfilamiento',
            name='logo_agente',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp/agentes'),
        ),
        migrations.AddField(
            model_name='perfilamiento',
            name='nombre_agente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfilamiento',
            name='pagina_web',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfilamiento',
            name='telefono_agente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
