# Generated by Django 5.0.7 on 2024-11-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andresapp', '0027_fichatecnica_cargo_en_la_agencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='cargo_en_la_agencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infoextra',
            name='ciudad_y_estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infoextra',
            name='email_agente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infoextra',
            name='logo_agente',
            field=models.ImageField(blank=True, null=True, upload_to='andresapp/agentes'),
        ),
        migrations.AddField(
            model_name='infoextra',
            name='nombre_agente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infoextra',
            name='pagina_web',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infoextra',
            name='telefono_agente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='antiguedad',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='distribucion_materiales',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='infraestructura_zona',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='instalaciones_especiales',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='situacion_legal',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='superficie_construccion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='superficie_terreno',
            field=models.CharField(max_length=250),
        ),
    ]
